Fix compilation error with old libnl
libnl commit b4802a17a765 ("nl: add "const" specifier for nla_policy
argument of parse functions") added 'const' qualifier to 'struct
nla_policy *' argument of the various *_parse() functions.

However, this commit is only present in libnl-3.5, whereas some
distributions are still shipping older versions.

This results in compilation errors such as:

```
dwdump.c:219:8: error: passing argument 5 of ‘genlmsg_parse’ discards
‘const’ qualifier from pointer target type
[-Werror=discarded-qualifiers]
```

Fix this by removing 'const' qualifier from the netlink attributes
policy structures in dwdump utility source. This is consistent with main
dropwatch utility source.

Fixes: 199440959a28 ("Add dwdump utility to dump kernel dropped packets to a file")
Signed-off-by: Ido Schimmel <idosch@mellanox.com>